= Installationsguide für Backend und PostgreSQL

Diese Anleitung beschreibt die manuelle Installation des Backends auf einem (möglichst "frischen") Ubuntu Server.

== Voraussetzungen

Bevor du beginnst, stelle sicher, dass folgende Voraussetzungen erfüllt sind:

1. Ein Ubuntu-Server (oder LXC-Container oder eine VM) mit Root-Zugriff.
2. Eine funktionierende Internetverbindung.
3. Möglichkeit der Konfiguration der Firewall.

== Angestrebte Verzeichnisstruktur

Mit den folgenden Schritten soll diese Verzeichnisstruktur erreicht werden:

[source,asciidoc]
----
.
├── /home/logbuch
│   ├── modellflug-logbuch
│   │   ├── bin
│   │   │   └── modellflug-logbuch
│   │   ├── lib
│   │   └── config
│   │       └── config.toml
└── ...
----

und das Systemd Unit File bei `/etc/systemd/system/logbuch.service`.

== Schritt 0: Separaten Nutzer anlegen

Es wird empfohlen, einen separaten Nutzer für den Backend-Server zu erstellen:

[source,shell]
----
sudo useradd -m logbuch
----

== Schritt 1: Update und Upgrade des Systems

Führe zuerst ein Update und Upgrade des Systems durch:

[source,shell]
----
sudo apt update
sudo apt upgrade -y
----

== Schritt 2: Installieren von Java

Der Backend-Server benötigt Java, um ausgeführt zu werden. Installiere OpenJDK:

[source,shell]
----
sudo apt install openjdk-17-jdk -y
----

Überprüfe die Installation:

[source,shell]
----
java --version
----

== Schritt 3: Installieren und Konfigurieren von PostgreSQL

Installiere PostgreSQL als Datenbankserver:

[source,shell]
----
sudo apt install postgresql -y
----

Starte und aktiviere den PostgreSQL-Dienst:

[source,shell]
----
sudo systemctl enable --now postgresql
----

== Schritt 4: Erstellen einer Datenbank und eines Benutzers in PostgreSQL

Wechsle zum PostgreSQL-Benutzer und öffne die PostgreSQL-Shell:

[source,shell]
----
sudo -i -u postgres
psql
----

Erstelle eine neue Datenbank und einen neuen Benutzer:

[source,sql]
----
CREATE DATABASE logbook_db;
CREATE USER myuser WITH ENCRYPTED PASSWORD 'SET_PASSWORD_HERE';
GRANT ALL PRIVILEGES ON DATABASE logbook_db TO logbook_user;
----

Beende die PostgreSQL-Shell:

[source]
----
q
----

Wechsle zurück zum vorherigen Benutzer:

[source,shell]
----
exit
----

== Schritt 5: Installieren des Backend-Servers

Lade das gepackte Backend-Projekt aus den GitHub Releases herunter. Das Projekt liegt als `.tar.gz` oder `.zip` Datei vor. Lade die Datei auf deinen Server hoch und entpacke sie:

[source,shell]
----
# für eine .tar.gz Datei
tar -xvzf releasename.tar.gz

# für eine .zip Datei
unzip releasename.zip
----

Benenne das entpackte Verzeichnis um und navigiere in das Verzeichnis:

[source,shell]
----
mv releasename modellflug-logbuch
cd modellflug-logbuch
----

Stelle sicher, dass die Datei `bin/modellflug-logbuch` ausführbar ist:

[source,shell]
----
chmod +x bin/modellflug-logbuch
----

== Schritt 6: Konfigurieren des Backend-Servers

Führe den Server einmal manuell aus um die Konfigurationsdatei zu generieren:

[source,shell]
----
./bin/modellflug-logbuch
----

Bearbeite die TOML-Konfigurationsdatei `config.toml`, um die Datenbankverbindungsdaten und andere Einstellungen festzulegen. Beispiel:

[source,toml]
----
# The time zone to use for the application.
# If not set, the system default is used.
# See https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/-time-zone/-companion/of.html for more information.
timeZone = "Europe/Berlin"

[database]
  serverName = "localhost"
  # The PostgreSQL default port is 5432.
  port = 5432
  username = "logbook_user"
  password = "SET_PASSWORD_HERE"
  # The name of the database to use. (You chose this during database setup.)
  databaseName = "logbook_db"

[server]
  # The port the server should listen on.
  port = 8080
  # In development mode the server runs without many security features.
  # This is useful for testing and debugging in local environments.
  developmentMode = false
----

Stelle sicher, dass der `developmentMode` auf `false` gesetzt ist.

== Schritt 7: Server als Dienst einrichten

Es ist ratsam, den Backend-Server als Systemdienst zu konfigurieren, damit er automatisch startet:

Erstelle eine neue Dienstdatei:

[source,shell]
----
sudo nano /etc/systemd/system/logbuch.service
----

Füge folgendes in *angepasster* Form in die Datei ein:

[source,ini]
----
[Unit]
Description=Modellflug Logbuch
After=network.target

[Service]
User=your-username
ExecStart=/your/path/bin/modellflug-logbuch
WorkingDirectory=/your/path/project
Restart=unless-stopped

[Install]
WantedBy=multi-user.target
----

Aktualisiere die Systemdienste und starte den Dienst:

[source,shell]
----
sudo systemctl daemon-reload
sudo systemctl enable --now logbuch
----

== Schritt 8: Überprüfung

Überprüfe, ob der Server läuft:

[source,shell]
----
sudo systemctl status logbuch
----

Besuche schließlich deine Server-IP oder Domain auf Port 8080 (oder dem in deinem Projekt konfigurierten Port), um sicherzustellen, dass der Ktor-Server und das eingebettete Frontend korrekt laufen.

== Schritt 9: Reverse Proxy (optional)

Wenn du den Ktor-Server über einen Reverse Proxy wie Nginx oder Apache bereitstellen möchtest, konfiguriere den Proxy entsprechend.

Falls der jeweilige Modellflugverein bereits einen Webserver bzw. Reverse Proxy betreibt, sollte dieser genutzt werden.

*Nginx Beispiel*

Erstelle eine neue Konfigurationsdatei und füge z.B. folgendes in die Datei ein:

[source,nginx]
----
server {
    listen 80;
    server_name your-domain.com;

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
----

*Apache Beispiel*

Erstelle eine neue Konfigurationsdatei und füge z.B. folgendes in die Datei ein:

[source,apache]
----
<VirtualHost *:80>
    ServerName your-domain.com

    ProxyPreserveHost On
    ProxyPass / http://localhost:8080/
    ProxyPassReverse / http://localhost:8080/
</VirtualHost>
----
