@startuml component_diagramm

node "Proxmox Server" {
    package "LXC Container" {
        readsWrites -u- [Database]
        communicates -u- [Backend]
    }
}

node "Smartphone" {
    [Frontend]
}

requestsData -l- [WeatherStation]


Backend .l. requestsData
Backend .u. readsWrites
Frontend .u. communicates
HTTPS -r- Frontend
SQLServerManagement -r- Database
@enduml