@startuml

participant Pilot_2 as p2
participant Pilot_1 as p1
participant Pilot_3 as p3

p1 -> p2: Abgabe Flugleiterrolle anfragen 
p1 -> p3: Abgabe Flugleiterrolle anfragen 
p3 -> p1: Ablehnen
p2 -> p1: Annehmen
p1 -> p2: Abgabe Flugleiterrolle bestätigen

@enduml