@startuml
skinparam packageStyle rectangle

package "Web Frontend" {
    [HomePage.vue] -up-> [LoginPage.vue]
    [LoginPage.vue] -right-> [RegistrationPage.vue]
    [HomePage.vue] -down-> [ListProtocolsPage.vue]
    [HomePage.vue] -right-> [CreateProtocolToProtocolPage.vue]
    [CreateProtocolPage.vue] -down-> [CompleteProtocolPage.vue]
}

package "Application Backend" {
    [DatabaseHandler.kt]
    [FlightlogRequest.kt] -up-> [DatabaseHandler.kt]
    [ProfileRoutes.kt] -right-> [DatabaseToHandler.kt]
    [AdminRoutes.kt] -left-> [DatabaseHandler.kt]
}

"Web Frontend" ..> "Application Backend" : <<use>>
"Application Backend" ..> [Database] : <<use>>
@enduml
