= System-Wide Requirements

include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute

ifndef::docs-requirements[:docs-requirements: ../requirements]

== Einführung
In diesem Dokument werden die systemweiten Anforderungen für das Projekt {project-name} spezifiziert. Die Gliederung erfolgt nach der FURPS+ Anforderungsklassifikation:

* Systemweite funktionale Anforderungen (F),
* Qualitätsanforderungen für Benutzbarkeit, Zuverlässigkeit, Effizienz und Wartbarkeit (URPS) sowie
* zusätzliche Anforderungen (+) für technische, rechtliche, organisatorische Randbedingungen

NOTE: Die funktionalen Anforderungen, die sich aus der Interaktion von Nutzern mit dem System ergeben, sind als Use Cases in einem link:{docs-requirements}/use-case_model[separaten Dokument] festgehalten.



== Systemweite funktionale Anforderungen
//Angabe von system-weiten funktionalen Anforderungen, die nicht als Use Cases ausgedrückt werden können. Beispiele sind Drucken, Berichte, Authentifizierung, Änderungsverfolgung (Auditing), zeitgesteuerte Aktivitäten (Scheduling), Sicherheit / Maßnahmen zum Datenschutz

// tag::swfa1[]
* *SWFA-1:* Das System muss Accountdaten sowie Protokolle dauerhaft speichern
// end::swfa1[]
** Zur Überprüfung wird die Datenbank mit Testdaten gefüllt. Nach dem Neustart müssen die Daten weiterhin vorliegen.
// tag::swfa2[]
* *SWFA-2:* Piloten müssen ihre eigenen Protokolle bearbeiten können, aber nicht die anderer Nutzer
// end::swfa2[]
** Zur Überprüfung wird ein Protokoll mit einem Pilotenaccount erstellt. Danach muss mit demselben Account das Bearbeiten des Protokolls möglich sein.
// tag::swfa3[]
* *SWFA-3:* Das System muss die Daten zu den Protokollen korrekt und vollständig erfassen und speichern
// end::swfa3[]
** Zur Überprüfung wird die Datenbank mit Testdaten gefüllt. Zudem werden die gleichen Daten lokal bei einem Entwickler gespeichert. Nach einem Neustart der Datenbank werden die Daten verglichen. Die Daten müssen auf der Datenbank unverändert vorliegen.
// tag::swfa4[]
* *SWFA-4:* Die Flugleiter-Regelungen müssen eingehalten werden, ein Admin oder ein Protokolleur soll das überprüfen können
// end::swfa4[]
** Zur Überprüfung erstellt ein Admin oder ein Protokolleur ein Tagesprotokoll. Dort kann er einsehen, ob die Flugleiter-Regelungen eingehalten wurden. Dafür muss er die Flugleiter-Zeiten mit den Protokollen zeitlich abgleichen.

== Qualitätsanforderungen für das Gesamtsystem
//Qualitätsanforderungen repräsentieren das "URPS" im FURPS+ zu Klassifikation von Anforderungen

=== Benutzbarkeit (Usability)
//Beschreiben Sie Anforderungen für Eigenschaften wie einfache Bedienung, einfaches Erlernen, Standards für die Benutzerfreundlichkeit, Lokalisierung (landesspezifische Anpassungen von Sprache, Datumsformaten, Währungen usw.)

* *NFAU-1:* Im Hauptmenü sollten alle möglichen Aktionen auf einen Blick übersehbar sein
** Zur Überprüfung wird das fertige Hauptmenü in einer realistischen Umgebung aufgerufen und untersucht, ob alle Aktionen auf einen Blick erfassbar sind.

* *NFAU-2:* Texte müss auf einem Smartphone auf bequemer Armlängenentfernung lesbar und Funktionen benutzbar sein
** Zur Überprüfung wird ein Testnutzer einige Anwendungsfälle auf seinem Smartphone auf Armlänge gehalten durchführen.

* *NFAU-3:* Die Benutzung des Systems sollte selbst für technische Laien verständlich sein
** Zur Überprüfung wird ein Testnutzer, der nicht gewohnt ist mit technischen Geräten umzugehen, einige Anwendungsfälle in dem System durchführen, ohne dabei Anwendungshilfe zu erhalten.

* *NFAU-6:* Der Benutzer sollte nach Öffnen der Anwendung mit 2 Klicks bereits ein Protokoll erstellen können
** Zur Überprüfung wird ein Testnutzer aufgefordert ein Protokoll zu erstellen, indem er nur 2 Klicks/Touches verwendet.

=== Zuverlässigkeit (Reliability)
// Zuverlässigkeit beinhaltet die Fähigkeit des Produkts und/oder des Systems unter Stress und ungünstigen Bedingungen am laufen zu bleiben. Spezifizieren Sie Anforderungen für zuverlässige Akzeptanzstufen, und wie diese gemessen und evaluiert werden. Vorgeschlagene Themen sind Verfügbarkeit, Häufigkeit und Schwere von Fehlern und Wiederherstellbarkeit.

* *NFAR-1:* Es darf sich kein Nutzer mit falschem Benutzernamen oder Passwort anmelden können.
** Zur Überprüfung wird die Anmeldung mit einem falschen Benutzernamen und/oder einem falschen Passwort durchgeführt.
* *NFAR-2:* Es dürfen keine unmöglichen Zeitspannen angegeben werden
** Zur Überprüfung wird versucht ein Protokoll über 10 Jahre zu erstellen.

=== Effizienz (Performance)
// Die Performanz Charakteristiken des Systems sollten in diesem Bereich ausgeführt werden. Beispiele sind Antwortzeit, Durchsatz, Kapazität und Zeiten zum Starten oder Beenden.

// tag::nfap1[]
* *NFAP-1:* Das System sollte in der Lage sein, Protokolle sofort abzuspeichern und auszugeben
// end::nfap1[]
** Zur Überprüfung wird ein Testnutzer ein Protokoll erstellen. Es sollte direkt danach aufgelistet und auffindbar sein.
// tag::nfap2[]
* *NFAP-2:* Seitenwechsel in der Anwendung müssen schnell erfolgen, sodass kein gravierender Unterschied zu einer nativen Mobile-App feststellbar ist
// end::nfap2[]
** Zur Überprüfung könnten ganz schnell die Seiten gewechselt werden und gleichzeitig der Progress-Indicator des Browsers beobachtet werden

=== Wartbarkeit (Supportability)
// Dieser Bereich beschreibt sämtliche Anforderungen welche die Supportfähigkeit oder Wartbarkeit des zu entwickelnden Systems verbessern, einschließlich Anpassungsfähigkeit und Erweiterbarkeit, Kompatibilität, Skalierbarkeit und Anforderungen bezüglich der System Installation sowie Maß an Support und Wartbarkeit.

// tag::nfas1[]
* *NFAS-1:* Das System sollte mit wenig Zeitaufwand administrierbar sein
// end::nfas1[]
** Zur Überprüfung wird eine Wartungssitzung simuliert und überprüft, dass der Zeitaufwand für diese im Rahmen bleibt. (2h-4h pro Saison?)


== Zusätzliche Anforderungen

=== Einschränkungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* System ist in die bereits vorhandene Proxmox Infrastruktur zu integrieren
** soll darin in einem LXC Container laufen
* keine Vorgaben für die Programmiersprache von Frontend und Backend

=== Rechtliche Anforderungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Datenschutz soll durch Login mit Benutzername und Passwort ermöglicht werden
* die standardisierten Regeln für Flugmodelle müssen eingehalten werden
* es soll eine Open-Source-Lizenz verwendet werden
