= Use-Case Model: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Allgemeine Informationen
// ...


== Identifizierte Use Cases
// Liste aller identifizierten Use Cases (priorisiert)
* *UC01*: Pilot registrieren
* *UC02*: Pilot anmelden
* *UC03*: Protkoll anlegen
* *UC04*: Protokoll einsehen
* *UC05*: Flugleiter bestimmen


== Use Case Diagramm
// ...

.Use-Case_Diagramm: gesamte Lösung
[plantuml, "{diagramsdir}/gesamter Use-Case", svg]
....
@startuml
left to right direction
"Admin" as ac01
"Pilot" as ac02
package Webapp-Frontend {
    "UC02 Pilot anmelden" as (uc02) 
    "UC03 Protokoll anlegen" as (uc03)
    "UC05 Flugleiter bestimmen" as (uc05)
    "UC06 Pilot abmelden" as (uc06)
}

package Webserver-Backend {
    "UC01 Pilot registrieren" as (uc01)
    "UC04 Protokolle einsehen" as (uc04)
    "UC07 Pilotendaten modifizieren" as (uc07)
    "UC08 Pilot deaktivieren" as (uc08)
    "UC90 Protokoll wird gespeichert" as (uc90)
    "UC91 Protokolle werden abgefragt" as (uc91)
    "UC92 Piloten-Account wird gespeichert" as (uc92)
    "UC93 Flugleitung wird zugeteilt" as (uc93)
}
ac01 -d-> uc01
ac01 -d-> uc04
ac01 -d-> uc07
ac01 -d-> uc08
ac02 -d-> uc02
ac02 -d-> uc06
uc01 -u-> ac02
uc01 .d.> uc92 :extends
uc02 .l.> uc03 :inlcude
uc03 .l.> uc05 :extends
uc03 .d.> uc90 :extends
uc04 .d.> uc91 :extends
uc05 .d.> uc93 :extends
uc06 .r.> uc05 :include
uc91 -r-> uc90
uc93 -u-> ac02
@enduml
....

//Fügen Sie nachfolgend alle detaillierten Use-Cases per Include ein.
//Dafür sollten Sie pro Use-Case eine Datei anlegen, die auf dem use_case_01.inc.adoc Template basiert.

////
Mit `<<<` wird im PDF ein Seitenumbruch erzeugt.
Zwischen `include::...` und dem darauf folgenden `<<<` muss sich eine Leerzeile befinden. Fehlt diese, werden unter Umständen die erste Überschriften aus der inkludierten Datei nicht korrekt übernommen.
Ein `include` entfernt am Anfang und Ende eine möglich Leerzeile, was in Kombination mit `<<<` zu Fehlern führen kann.
////

<<<
include::use_case_01.inc.adoc[]

<<<
include::use_case_02.inc.adoc[]

//<<<
//include::use_case_03.inc.adoc[]

//<<<
//include::use_case_04.inc.adoc[]

//<<<
//include::use_case_05.inc.adoc[]

//<<<
//include::use_case_06.inc.adoc[]

//<<<
//include::use_case_07.inc.adoc[]

//<<<
//include::use_case_08.inc.adoc[]

//<<<
//include::use_case_09.inc.adoc[]

//<<<
//include::use_case_10.inc.adoc[]
