ifndef::main-document[include::../_includes/default-attributes.inc.adoc[]]


== Use-Case: UC02 Pilot anmelden

=== Kurzbeschreibung
In diesem Use-Case wird der Vorgang bei der Anmeldung eines *Piloten* beim Betreten des Flugplatzes beschrieben.

=== Kurzbeschreibung der Akteure

==== Pilot
Ein Pilot ist der Benutzer des Systems und des Flugplatzes.
Er kann Veränderungen an seinem Profil vornehmen, jedoch nicht am Gesamtsystem.

=== Vorbedingungen
. UC01 ist erfüllt
. *Pilot* ist noch nicht angemeldet
. *Pilot* kennt seinen Nutzernamen und sein Passwort

=== Standardablauf (Basic Flow)

. Der Use Case beginnt, wenn *Pilot* die Webapp öffnet um sich anzumelden. Die Webapp kann über einen QR Code geöffnet werden.
. Der *Pilot* gibt seinen Nutzernamen ein.
. Der *Pilot* gibt sein Passwort ein.
. In der Datenbank wird überprüft, ob es einen solchen Nutzer (definiert durch Nutzername und Passwort) gibt.
. IF *Pilot* existiert
.. Der *Pliot* wird angemeldet.
. Die Anmeldung wird protokolliert.
. Der Use Case ist abgeschlossen.

=== Alternative Abläufe


==== Nutzer existiert nicht (Schritt 5)
. IF *Pilot* existiert nicht
.. Ausgabe Fehlermeldung, Anmeldung erfolgt nicht

=== Wesentliche Szenarios


==== Standartmäßige Anmeldung
. Sc1: *Pilot* XX trifft auf dem Flugplatz ein. XX öffnet die Webapp über einen Browser oder mithilfe des QR Codes. XX gibt seine Nutzerdaten ein und wird bei deren Richtigkeit angemeldet. Die Anmeldung wird protokolliert und er kann den Flugplatz bis zu seiner Abmeldung nutzen, solange UC05 nichts anderes festlegt.

==== fehlgeschlagene Anmeldung
. Sc2: *Pilot* XX trifft auf dem Flugplatz ein. XX öffnet die Webapp über einen Browser oder mithilfe des QR Codes. XX gibt seine Nutzerdaten ein und versucht sich anzumelden. Die Anmeldung schlägt aufgrund falscher Anmeldedaten fehl. Eine Fehlermeldung wird ausgegeben.

=== Nachbedingung
Der Pilot ist angemeldet und kann alle Funktionalitäten nutzen, zu denen ein Pilot berechtigt ist. Im Backend muss nun bekannt sein, dass sich mindestens ein Pilot auf dem Flugplatz befindet.

=== Besondere Anforderungen

==== Usability
* Der Use Case gehört zu der grundlegenden Funktionalität des _Systems_ und muss daher für jeden *Piloten* einfach und verständlich sein.

---

(Zur Erstellung des Use Cases wurde sich am Use Case 01 des Vorgängerprojektes orientiert)



