ifndef::main-document[include::../_includes/default-attributes.inc.adoc[]]

== Use-Case: UC05 Flugleiter bestimmen

=== Kurzbeschreibung
In diesem Use-Case wird der Vorgang der standartmäßigen Bestimmung eines Flugleiters beschrieben und wie dieser Status bei mehreren Piloten übergeben werden kann.

=== Kurzbeschreibung der Akteure

==== Pilot
Ein Pilot ist der Benutzer des Systems und des Flugplatzes.
Er kann Veränderungen an seinem Profil vornehmen, jedoch nicht am Gesamtsystem.

==== Flugleiter
Der Akteur "Flugleiter" ist ein Pilot, der den Flugplatz nicht aktiv nutzt, sondern die Verantwortung über die Flugaktivitäten aller Piloten auf dem Platz hat. Er darf *selber nicht fliegen*.

Die Piloten müssen sich untereinander apsprechen, wer den Posten übernimmt. Ab 3 Piloten wird in der App eine Meldung angezeigt, dass dringend ein Flugleiter benötigt wird. Erst ab 8 Piloten ist der Flugleiter gesetzlich vorgeschrieben.

=== Vorbedingung
. mehrere Piloten müssen sich auf dem Flugplatz befinden.

=== Standartablauf
. Piloten betreten den Flugplatz und melden sich an (UC02)
. ab 3 Piloten wird die Meldung angezeigt, dass ein Flugleiter benötigt wird
. Piloten kommunizieren untereinander, wer den Posten übernimmt
. Der künftige Flugleiter ernennt sich zum Flugleiter, indem er den Button "Als Flugleiter anmelden" betätigt
. Er liest die Erläuterung und bestätigt mit "Ja, Anmelden" und ist ab dem Zeitpunkt Flugleiter
. Piloten melden sich nach und nach ab
. Der Flugleiter meldet sich als Flugleiter mit dem Button "Als Flugleiter abmelden" ab
. Der Use Case ist abgeschlossen.

=== Alternative Abläufe

==== Flugleiter übertragen
. Piloten können sich absprechen, wer den Flugleiterposten ausübt.
. Der aktuelle Flugleiter meldet sich nach Absprache als Flugleiter ab
. IF es gibt mehr als 2 Piloten auf dem Flugplatz
..  Meldung, dass Flugleiter nötig ist, wird angezeigt
. Der andere Pilot kann sich nun als Flugleiter anmelden

==== 2 Personen wollen sich als Flugleiter anmelden
. Pilot ist als Flugleiter angemeldet
. Ein anderer Pilot möchte sich ebenfalls als Flugleiter anmelden
. zugehöriger Button funktioniert erst, wenn erster Flugleiter abgemeldet ist -> vorheriger Wechsel nicht möglich

=== Wesentliche Szenarios

==== Standartmäßige Bestimmung des Flugleiters mit Abmeldung
Sc.1: 3 Piloten betreten den Flugplatz. Sie bekommen die Meldung angezeigt, dass ein Flugleiter benötigt wird. Sie kommunizieren untereinander, wer den Posten übernimmt. Der künftige Flugleiter ernennt sich zum Flugleiter, indem er den Button "Als Flugleiter anmelden" betätigt. Er liest die Erläuterung und bestätigt mit "Ja, Anmelden" und ist ab dem Zeitpunkt Flugleiter. Die anderen Piloten fliegen. Die anderen Piloten melden sich nach und nach ab. Der Flugleiter meldet sich als Flugleiter mit dem Button "Als Flugleiter abmelden" ab.

==== Falsche Nutzung des Flugleiters
Sc.2: 3 Piloten betreten den Flugplatz. Sie bekommen die Meldung angezeigt, dass ein Flugleiter benötigt wird. Sie ignorieren die Meldung und sorgen dadurch dafür, dass der Flugplatz im Nachhinein Probleme bekommen kann. Der Admin kann diese Missachtung im Nachhinein sehen und den Piloten darauf ansprechen, um deratige Vorfälle in Zukunft zu vermeiden.

=== Nachbedingungen
. Bei erfolgreicher Durchführung des Use Case müssen folgende 
Nachbedingungen erfüllt sein:
.. Es existiert maximal ein Flugleiter, der vom System erfasst wurde

=== Besondere Anforderungen

==== Abmeldung Flugleiter

Bevor der aktuelle Flugleiter den Flugplatz verlässt muss er unbedingt seine Rolle an einen anderen Piloten abgeben (1.5.1. Flugleiter übertragen), es sei denn es gibt weniger als 3 aktive Piloten.
