ifndef::main-document[include::../_includes/default-attributes.inc.adoc[]]

== Use-Case: UC05 Flugleiter bestimmen

=== Kurzbeschreibung
In diesem Use-Case wird der Vorgang der standartmäßigen Bestimmung eines Flugleiters beschrieben und wie dieser Status bei mehreren Piloten übergeben werden kann.

=== Kurzbeschreibung der Akteure

==== Pilot
Der Akteur "Pilot" nutzt den Flugplatz.

==== Flugleiter
Der Akteur "Flugleiter" ist ein Pilot, der den Flugplatz nicht aktiv nutzt, sondern die Verantwortung über die Flugaktivitäten aller Piloten auf dem Platz hat. Er darf *unter keinen Umständen selbst fliegen*.

Außnahme: Befindet sich *nur ein Pilot* auf dem Flugplatz, dann ist dieser Flugleiter, darf aber *trotzdem fliegen*.

Flugleiter können sich nur dann abmelden, wenn kein anderer Pilot angemeldet ist.

=== Vorbedingung
. mindestens 1 Pilot muss sich auf dem Flugplatz angemeldet haben. (UC02 erfüllt) 

=== Standardablauf (1 Pilot)
. Die Rolle Flugleiter wird dem Piloten automatisch zugewiesen.
. Der Flugleiter darf fliegen.
. Die Abmeldung ist ohne Probleme möglich.

=== Standartablauf (mehrere Piloten)
. Der als letztes angemeldete Pilot bekommt die Rolle Flugleiter automatisch zugewiesen.
. Der vorherige Flugleiter bekommt eine Nachricht, dass er kein Flugleiter mehr ist.
. Der Flugleiter darf nicht fliegen.
. Der Flugleiter kann sich nicht abmelden, erst, wenn er die Rolle Flugleiter abgegeben hat (Alternativer Ablauf 1.6.1), oder wenn er sich allein auf dem Flugplatz befindet. (Standartablauf 1.4 Schritt 3)

=== Alternative Abläufe

==== Flugleiter übertragen
. Piloten können sich absprechen, wer den Flugleiterposten ausübt. Dafür hat der aktuelle Flugleiter die Möglichkeit diesen zu übertragen.
. Der Flugleiter fragt über ein Dialogfester bei einen anderen Piloten an, ob dieser den Posten übernehmen möchte.
. Der andere Pilot kann diese Anfrage annehmen um Flugleiter zu werden. Bei Ablehnung bleibt der alte Flugleiter bestehen.
 

=== Wesentliche Szenarios

==== 1 Pilot nutzt den Flugplatz
. Pilot betritt den Flugplatz und meldet sich an (UC02)
. Pilot bekommt die Rolle Flugleiter zugewiesen
. Pilot fliegt
. Pilot meldet sich ab

==== Komplexes Szenario: 2 Piloten mit Übertragung Flugleiter
. Pilot1 betritt den Flugplatz und meldet sich an (UC02)
.. Pilot1 bekommt die Rolle Flugleiter zugewiesen
.. Pilot1 darf fliegen
. Pilot2 betritt den Flugplatz und meldet sich an (UC02)
.. Pilot2 bekommt die Rolle Flugleiter zugewiesen
.. Pilot2 darf nicht fliegen
. Pilot2 versucht sich abzumelden
.. Fehlermeldung: Erst Rolle Flugleiter übertragen
. Pilot2 fragt an, ob er die Rolle Flugleiter an Pilot1 übertragen kann
. Pilot1 bestätigt die Anfrage, wird Flugleiter, darf nicht mehr fliegen
. Pilot2 meldet sich ab
.. Pilot1 darf wieder fliegen
. Pilot1 meldet sich ab


=== Nachbedingungen
. Bei erfolgreicher Durchführung des Use Case müssen folgende 
Nachbedingungen erfüllt sein:
.. Es existiert maximal ein Flugleiter, der vom System erfasst wurde

=== Besondere Anforderungen

==== Abmeldung Flugleiter

Bevor der aktuelle Flugleiter den Flugplatz verlässt muss er unbedingt seine Rolle an einen anderen Piloten abgeben.
