ifndef::main-document[include::../_includes/default-attributes.inc.adoc[]]

== Use-Case: UC05 Flugleiter bestimmen

=== Kurzbeschreibung
In diesem Use-Case wird der Vorgang der standartmäßigen Bestimmung eines Flugleiters beschrieben und wie dieser Status bei mehreren Piloten übergeben werden kann.

=== Kurzbeschreibung der Akteure

==== Pilot
Ein Pilot ist der Benutzer des Systems und des Flugplatzes.
Er kann Veränderungen an seinem Profil vornehmen, jedoch nicht am Gesamtsystem.

==== Flugleiter
Der Akteur "Flugleiter" ist ein Pilot, der den Flugplatz nicht aktiv nutzt, sondern die Verantwortung über die Flugaktivitäten aller Piloten auf dem Platz hat. Er darf *nicht selber fliegen*.

Befinden sich *weniger als 3 Pilot* auf dem Flugplatz, dann ist der erste Pilot der sich angemeldet hatte der Flugleiter, darf aber *trotzdem fliegen*.
Es wird erst ab 3 aktiven Piloten auch ein Flugleiter benötigt, der nicht selber fliegen darf.

Flugleiter können sich nur dann abmelden, wenn kein anderer Pilot angemeldet ist.

=== Vorbedingung
. mindestens 2 Pilot muss sich bereits auf dem Flugplatz angemeldet haben. (UC02 erfüllt) 

=== Standardablauf (1 Pilot)
. Die Rolle Flugleiter wird dem Piloten automatisch zugewiesen.
. Der Flugleiter darf fliegen.
. Die Abmeldung ist ohne Probleme möglich.

=== Standartablauf (mehrere Piloten)
. Der als dritte angemeldete Pilot bekommt die Rolle Flugleiter automatisch zugewiesen.
. Der vorherige Flugleiter bekommt eine Nachricht, dass er kein Flugleiter mehr ist.
. Der Flugleiter darf nicht fliegen.
. Der Flugleiter kann sich nicht abmelden, erst, wenn er die Rolle Flugleiter abgegeben hat (Alternativer Ablauf 1.6.1), oder wenn er sich allein auf dem Flugplatz befindet. (Standartablauf 1.4 Schritt 3)

=== Alternative Abläufe

==== Flugleiter übertragen
. Piloten können sich absprechen, wer den Flugleiterposten ausübt. Dafür hat der aktuelle Flugleiter die Möglichkeit diesen zu übertragen.
. Der Flugleiter fragt über ein Dialogfester bei einen anderen Piloten an, ob dieser den Posten übernehmen möchte.
. Der andere Pilot kann diese Anfrage annehmen um Flugleiter zu werden. Bei Ablehnung bleibt der alte Flugleiter bestehen.
 

=== Wesentliche Szenarios

==== 1 Pilot nutzt den Flugplatz
. Pilot betritt den Flugplatz und meldet sich an (UC02)
. Pilot bekommt die Rolle Flugleiter zugewiesen
. Pilot fliegt
. Pilot meldet sich ab

==== Komplexes Szenario: 3 Piloten mit Übertragung Flugleiter
. Pilot1 und Pilot2 betreten den Flugplatz und melden sich an (UC02)
.. Pilot1 bekommt die Rolle Flugleiter zugewiesen
.. Pilot1 und Pilot2 dürfen fliegen
. Pilot3 betritt den Flugplatz und meldet sich an (UC02)
.. Pilot3 bekommt die Rolle Flugleiter zugewiesen
.. Pilot3 darf nicht fliegen
. Pilot3 versucht sich abzumelden
.. Fehlermeldung: "Erst Rolle Flugleiter übertragen"
. Pilot3 fragt an, ob er die Rolle Flugleiter an Pilot1 übertragen kann
. Pilot1 bestätigt die Anfrage, wird Flugleiter, darf nicht mehr fliegen
. Pilot3 meldet sich ab
.. Pilot1 darf wieder fliegen
. Pilot1 meldet sich ab


=== Nachbedingungen
. Bei erfolgreicher Durchführung des Use Case müssen folgende 
Nachbedingungen erfüllt sein:
.. Es existiert maximal ein Flugleiter, der vom System erfasst wurde

=== Besondere Anforderungen

==== Abmeldung Flugleiter

Bevor der aktuelle Flugleiter den Flugplatz verlässt muss er unbedingt seine Rolle an einen anderen Piloten abgeben, es sei denn es gibt weniger als 3 aktive Piloten.
