//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).
ifndef::main-document[include::../_includes/default-attributes.inc.adoc[]]


== Use-Case: UC01 Pilot registrieren

=== Kurzbeschreibung
//<Kurze Beschreibung des Use Case>

=== Kurzbeschreibung der Akteure

==== Admin
Admin administriert die Lösung.
Darunter fallen Aufgaben wie das registrieren neuer Piloten.

==== Pilot
Pilot entsteht durch diesen Use-Case.
Er ist der Standardnutzer der Lösung.

=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...

Die App muss mindestens im Prototypstadium sein.
Ein Admin-Akteur muss existieren.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn ein Admin einen Piloten-Account registrieren will.
. Der Admin erstellt einen Account für Piloten
. Ein Account für Piloten wurde erstellt
. Der Use Case ist abgeschlossen.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== <Alternativer Ablauf 1>
Wenn <Akteur> im Schritt <x> des Standardablauf <etwas macht>, dann
. <Ablauf beschreiben>
. Der Use Case wird im Schritt <y> fortgesetzt.

=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern

==== <Unterablauf 1>
. Admin betätigt Button "Account erstellen"
. Accounterstellung öffnet sich
. Admin gibt Daten ein (Name, Vorname, Flugleitererlaubnis, Tagesmitglied/Gast)
. Admin betätigt Button "Accounterstellung abschließen"
. Account wird vom System registiert

=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.

==== <Szenario 1>
. <Szenario 1, Schritt 1>
. …
. <Szenario 1, Schritt n>

=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.

==== Pilot ist erstellt
Ein Pilotenaccount wurde für den Akteur Pilot erstellt.
Der Account kann vom Akteur verwendet werden.

=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.

==== <Besondere Anforderung 1>


=== Use-Case-Diagramm

.Use-Case_Diagramm: UC01PilotRegistriert
[plantuml, "{diagramsdir}/UC01PilotRegistriert", svg]
....
@startuml
left to right direction
"Admin" as ac01
"Pilot" as ac02
package Webapp-Frontend {
    "UC01 Pilot registrieren" as (uc01)
}
package Webserver-Backend {
    "UC92 Pilotenaccount wird gespeichert" as (uc92)
}
ac01 -d-> uc01
uc01 -l-> ac02
uc01 -d-> uc92
@enduml
....

.Use-Case_Diagramm: gesamte Lösung
[plantuml, "{diagramsdir}/gesamter Use-Case", svg]
....
@startuml
left to right direction
"Admin" as ac01
"Pilot" as ac02
package Webapp-Frontend {
    "UC01 Pilot registrieren" as (uc01)
    "UC02 Pilot anmelden" as (uc02) 
    "UC03 Protokoll anlegen" as (uc03)
    "UC04 Protokolle einsehen" as (uc04)
    "UC05 Flugleiter bestimmen" as (uc05)
    "UC06 Pilot abmelden" as (uc06)
}

package Webserver-Backend {
    "UC90 Protokoll wird gespeichert" as (uc90)
    "UC91 Protokolle werden abgefragt" as (uc91)
    "UC92 Piloten-Account wird gespeichert" as (uc92)
    "UC93 Flugleitung wird zugeteilt" as (uc93)
}
ac01 -d-> uc01
ac01 -d-> uc04
ac02 -d-> uc02
ac02 -d-> uc06
uc01 -u-> ac02
uc01 -d-> uc92
uc02 -r-> uc03
uc02 -l-> uc05
uc03 -d-> uc90
uc04 -d-> uc91
uc05 -d-> uc93
uc06 -r-> uc05
uc91 -r-> uc90
uc92 -u-> uc02
uc93 -u-> ac02
@enduml
....