= Iteration Plan 07: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Meilensteine
//Meilensteine zeigen den Ablauf der Iteration, wie z.B. den Beginn und das Ende, Zwischen-Meilensteine, Synchronisation mit anderen Teams, Demos usw.

[%header, cols="3,1"]
|===
| Meilenstein | Datum

| Beginn der Iteration | KW 15
| Ende der Iteration | KW 17
|===


== Wesentliche Ziele

* 2.Termin mit Auftraggeber durchführen, vortsellen des Arbeitsstands
* Anfordrungen/ Änderungswünsche des Auftaggebers in Anforderungen aufnehmen, die vorhandene implentierung anpasen oder implementieren
* 2.Termin mit Coach durchführen
* Implementierung fortsetzten
* Durchführung eines Teambuildingevents


== Aufgabenzuordnung
//Dieser Abschnitt sollte einen Verweis auf die Work Items List enthalten, die die für diese Iteration vorgesehenen Aufgaben dokumentiert sowie die Zuordnung dieser Aufgaben zu Teammitgliedern. Alternativ können die Aufgaben für die Iteration und die Zuordnung zu Teammitgliedern in nachfolgender Tabelle dokumentiert werden - je nach dem, was einfacher für die Projektbeteiligten einfacher zu finden ist.

Die in dieser Iteration geplanten Aufgaben sind in der Work Items List dargestellt:

siehe *https://github.com/users/jakobkmar/projects/2/views/3?filterQuery=iteration%3A%22Iteration+2%22[Work Item List - Iteration 7]*

_alternativ:_ Die folgenden Aufgaben werden in dieser Iteration bearbeitet:

.Work Item List: Iteration 7
noch einzufügen


== Probleme (optional)
//Optional: Führen Sie alle Probleme auf, die in dieser Iteration adressiert werden sollen. Aktualisieren Sie den Status, wenn neue Probleme bei den täglichen / regelmäßigen Abstimmungen berichtet werden.

[%header, cols="2,1,3"]
|===
| Problem | Status | Notizen

| x | x | x
|===


== Bewertungskriterien

* Das Teambuildingevent stärkt das Verantwortungsbewusstsein aller Teammitglieder für das gesamte Team, persönliche Gespräche verbessern die Atmosphäre für kommende Meetings
* Der Auftraggeber ist mit dem aktellen Arbeitsstand zufrieden, keine Substantiellen Änderungen sind erforderlich
* Es wurden substantiellen fortschritte ebi der Implementierung von Frontend (insbes. UI) und Backend erzielt. 
* Im Choach Termin konnten wesentliuche Anforderungen und Bewertungskriterien an dieses Projekt identifiziert werden


== Assessment

[%header, cols="1,3"]
|===
| Assessment Ziel | Iteration 7

| Assessment Datum | TBD
| Teilnehmer | Projektmanagement, TBD
|===

*Beurteilung im Vergleich zu den Zielen*
beit im Teammeeting funktioniert, die arbeit am Projekt konnte erfolgreich fortgesetzt werden. 

ToDo

*Projektfortschritt*

ToDo

.Projektfortschritt: Iteration 5

ToDo
