== Reflexion zur Implementierung der Protokollierungs-Seiten

Im Rahmen unseres Projekts zur Entwicklung eines mobilen Logbuchs für den Modellflugplatz des Mfc-Rossendorf bestand eine meiner Hauptaufgaben darin, die <<frontend_pages>> im Frontend zu entwickeln und die dadurch notwendigen Änderungen im Backend durchzuführen. Diese Aufgabe war entscheidend für die Nutzererfahrung, da die Piloten ihre Anwesenheit schnell und einfach über ihr Smartphone protokollieren müssen. Dabei baute ich auf der Arbeit eines vorherigen Teammitglieds auf, welches die grundlegende Struktur und Implementierung der Routen inklusive einiger SQL-Requests vorbereitet hatte.

Diese Aufgaben fielen hauptsächlich in die Bereiche *Entwurf* und *Implementierung*. Während der Analysephase wurden die Anforderungen an die Protokollierungspages in Form von Use Cases spezifiziert. Anschließend erarbeitete ich im Rahmen des Entwurfs einen Plan für die Implementierung der Protokollierungspages. Auch die *Architektur* für die Kommunikation zwischen Frontend und Backend, welche im Kern auf einer klar getrennten Client-Server-Architektur basiert, wurde von mir entworfen und im link:https://github.com/jakobkmar/E09-modellflug-logbuch/blob/5c919056cb6d025a9497dbd48f8015d80bd9d852/docs/architecture/architecture_notebook.adoc[Architecture Notebook] festgehalten. In der Implementierung wurde dieser Entwurf ohne Änderungen umgesetzt.

==== Lösungsweg

Ich begann vor allem aufbauend auf dem link:https://github.com/jakobkmar/E09-modellflug-logbuch/blob/5c919056cb6d025a9497dbd48f8015d80bd9d852/docs/requirements/use_case_03.inc.adoc[Use Case 02], an welchem ich in SE I schon mitgewirkt hatte. Weiterhin bot der link:https://github.com/jakobkmar/E09-modellflug-logbuch/blob/5c919056cb6d025a9497dbd48f8015d80bd9d852/docs/requirements/images/wireframes/protokoll_anlegen.jpg[Wireframe "Protokoll anlegen"] eine visuelle Grundlage. Durch die Vorarbeit eines Teamkollegen, welcher die link:https://github.com/jakobkmar/E09-modellflug-logbuch/commit/1098849f294aa6eb1e70e4a3ebc0ab8bd550fd31[grundlegende Struktur] der Routen im Backend geschaffen hatte, bot sich mir bereits eine gute Basis. Mit der link:https://github.com/jakobkmar/E09-modellflug-logbuch/pull/89[Durchführung eines Code Reviews] des dazugehörigen Pull Requests und Feedback im persönlichen Gespräch konnte ich sicherstellen, dass die Implementierung den Anforderungen entsprach und gleichzeitig wertvolle Einblicke in die bestehende Implementierung gewinnen.

===== Frontend-Entwicklung

[#frontend_pages, reftext=Protokollierungspages]
- *`CreateFlightPage.vue`* link:https://github.com/jakobkmar/E09-modellflug-logbuch/blob/5c919056cb6d025a9497dbd48f8015d80bd9d852/src/frontend/src/pages/flight/CreateFlightPage.vue[(->)]: Ermöglicht es den Piloten, einen neuen Flug zu beginnen. Sie umfasst Eingabemasken für Datum und Zeit, die Auswahl des Flugzeugtyps, die Erfassung der Erste-Hilfe-Ausrüstung und die Integration einer Unterschriftenfunktion per Touch, für welche ich einen separaten link:https://github.com/jakobkmar/E09-modellflug-logbuch/blob/5c919056cb6d025a9497dbd48f8015d80bd9d852/src/frontend/src/components/MouseCanvas.vue[Vue Component `MouseCanvas.vue` entwickelte].
- *`CompleteFlightPage.vue`* link:https://github.com/jakobkmar/E09-modellflug-logbuch/blob/5c919056cb6d025a9497dbd48f8015d80bd9d852/src/frontend/src/pages/flight/CompleteFlightPage.vue[(->)]: Option für Piloten, einen aktiven Flug abzuschließen. Sie zeigt die Details des aktuellen Fluges an und bietet die Möglichkeit, zusätzliche Notizen hinzuzufügen.
- *`ListOwnFlightsPage.vue`* link:https://github.com/jakobkmar/E09-modellflug-logbuch/blob/5c919056cb6d025a9497dbd48f8015d80bd9d852/src/frontend/src/pages/flight/ListOwnFlightsPage.vue[(->)]: Ermöglicht es den Piloten, alle bisherigen eigenen Flüge einzusehen und zu filtern. Sie umfasst eine Filterfunktion nach Datum und eine Liste der protokollierten Flüge, die in Form von FlightCards angezeigt werden. Dies erleichtert den Piloten die Verwaltung ihrer eigenen Flugeinträge.
- *`ListTodayFlightsPage.vue`* link:https://github.com/jakobkmar/E09-modellflug-logbuch/blob/5c919056cb6d025a9497dbd48f8015d80bd9d852/src/frontend/src/pages/flight/ListTodayFlightsPage.vue[(->)]: Zeigt alle heute aktiven und abgeschlossenen Flüge an, was vor allem für Vereinsmitglieder vor Ort eine relevante Information ist.

Für die Umsetzung dieser Pages nutzte ich das Vue.js Framework. Dabei achtete ich auf eine klare Trennung (Separation of Concerns) und Wiederverwendbarkeit von Komponenten, um die Wartbarkeit und Erweiterbarkeit des Codes zu gewährleisten, wobei sich die Vorteile der Vue Components auch schon während der iterativen Entwicklung und daraus resultierenden Änderungen zeigten. Da z.B. alle Pages Flugeinträge anzeigen müssen, extrahierte ich die Darstellung der Flugeinträge in einen link:https://github.com/jakobkmar/E09-modellflug-logbuch/blob/5c919056cb6d025a9497dbd48f8015d80bd9d852/src/frontend/src/components/FlightCard.vue[eigenen Vue Component `FlightCard.vue`], um Redundanzen zu vermeiden.

===== Backend-Änderungen

Zur Unterstützung der neuen Frontend-Funktionalitäten musste ich die link:https://github.com/jakobkmar/E09-modellflug-logbuch/blob/5c919056cb6d025a9497dbd48f8015d80bd9d852/src/backend/src/main/kotlin/de/mfcrossendorf/logbook/routes/FlightLogRoutes.kt[API-Endpunkte in `FlightLogRoutes.kt`] erweitern. Dabei setze ich (wie mein Teamkollege) auf den deklarativen Ansatz von Ktor, um die Routen und ihre Parameter klar zu definieren. Desweiteren setzen wir auf einen funktionalen Stil, um die Lesbarkeit und Sicherheit in der Implementierung zu gewährleisten.

Da die Input-Validation zur Sicherung der Datenintegrität und Konsistenz im Backend stattfindet, fügte ich mehrere link:https://github.com/jakobkmar/E09-modellflug-logbuch/tree/5c919056cb6d025a9497dbd48f8015d80bd9d852/src/backend/src/main/kotlin/de/mfcrossendorf/logbook/validation[Validierungsregeln] hinzu. Während der Implementierung der Frontend-Pages ergab sich, dass mehr spezifische Datenbankabfragen gefragt waren, als ursprünglich umgesetzt wurden, link:https://github.com/jakobkmar/E09-modellflug-logbuch/blob/5c919056cb6d025a9497dbd48f8015d80bd9d852/src/backend/src/main/sqldelight/de/mfcrossendorf/flight.sq#L26-L87[diese fügte ich deshalb hinzu]. Der Vorteil der spezifischen Abfragen ergibt sich aus einem eingeschränkten Scope, wodurch die Abfragen effizienter und sicherer sind. Für jede SQL-Abfrage wird durch das SQLDelight Compiler Plugin automatisch eine type-safe Kotlin-Funktion generiert, um damit die Aufrufe und Responses mit korrekten Feldern und Datentypen zu versehen.

Als besonders gute Entscheidung in der Architektur stellte sich heraus, dass wir die Schemata für Requests und Responses in einem link:https://github.com/jakobkmar/E09-modellflug-logbuch/tree/5c919056cb6d025a9497dbd48f8015d80bd9d852/src/backend/common-data[geteilten Kotlin Modul] vom Backend getrennt definierten. Da Kotlin Multiplatform Module auch zu TypeScript `.d.ts` Typdefinitionen kompiliert werden können, konnten wir so die Typsicherheit zwischen Frontend und Backend erhöhen und garantieren, dass jeder Request und jede Response die korrekte Struktur aufweist. Dies war insbesondere für die Teamarbeit von Vorteil, da Änderungen für jeden sofort durch den Compiler klar waren.

==== Bewertung

Meine Lösung hat erfolgreich funktioniert. Die Protokollierungspages wurden in mehreren link:https://github.com/jakobkmar/E09-modellflug-logbuch/blob/df913479575815eb4e436bf23cae7602f803e81b/docs/test/TeseCase05_TC05.adoc[Testszenarien] durch die verantwortlichen Tester überprüft und zeigten eine hohe Benutzerfreundlichkeit und Zuverlässigkeit. Die link:https://github.com/jakobkmar/E09-modellflug-logbuch/blob/7a4fe32263ac0c818cb9599a1b21985682043a9a/belegabgabe_se2/Einzelreflexionen/images/jakob/screenshot-create_flight_log.png[einfache Bedienung] wurde durch den Auftraggeber gelobt. Mithilfe der Input-Validierung erhält der Nutzer nun direkt und konkretes Feedback, _welche_ Daten _warum_ nicht korrekt sind.

Verbesserungswürdig ist der Punkt, dass aktuell das Don't Repeat Yourself (DRY) - Prinzip bei den Backend-Routen noch nicht vollständig umgesetzt ist. Dies ist dem geschuldet, dass für die spezifischen SQL-Requests durch das Kotlin Compiler Plugin jeweils ähnliche, aber komplett neue ORM Klassen generiert werden. Deswegen gibt es beim Auslesen der Daten aus diesen Klassen und dem Mapping auf die Response-Objekte noch Redundanzen. Abhilfe könnte hier ein generischeres, aber dadurch auch komplexeres, Mapping-Tool schaffen.

Der größte Erfolg war das konsequente Einsetzen von typisierten Tools, Bibliotheken und Sprachen. Dies beschleunigte insbesondere die Zusammenarbeit im Team bzw. zwischen Frontend und Backend. Trotz der strikten Trennung in Client und Server konnten so die Schnittstellen klar definiert, Änderungen per Compiler propagiert und die Gemeinsamkeiten (Request und Response Bodys) in einem geteilten Modul nur ein einziges Mal definiert werden.

Der deklarative und funktionale Programmierstil im Backend gefiel mir sehr gut. So konnte die Kohäsion der einzelnen Komponenten erhöht werden. Auch der Reaktive und Component-basierte Ansatz im Frontend mit Vue.js war sehr angenehm und führte zu einer klaren Struktur. Sowohl im Frontend als auch im Backend konnte die Kopplung zwischen den Komponenten sehr gering gehalten werden, was die Wartbarkeit, aber auch schon die iterative Entwicklung für uns erleichterte. Eine gute Lesbarkeit des Codes wurde erreicht, indem ich den den Kotlin Styleguide las, wir den IntelliJ Formatter verwendeten und link:https://github.com/jakobkmar/E09-modellflug-logbuch/blob/7a4fe32263ac0c818cb9599a1b21985682043a9a/src/frontend/.prettierrc.json[ich nutze Prettier] für das Frontend.

Durch das Projekt konnte ich insbesondere mein Verständnis für die Anforderungsanalyse, den Entwurf und die Definierung der Architektur _vor_ der Implementierung vertiefen. Ich hatte bereits vor dem Projekt Vorerfahrung in der Fullstack-Entwicklung, jedoch habe ich dort nie so strukturiert gearbeitet, speziell nicht nach dem OpenUP. Besonders geholfen haben mir bei der "Create Flight Page" die vorhandenen Use Cases. Aufgrund die bereits link:https://github.com/jakobkmar/E09-modellflug-logbuch/pull/59[früh feststehende Architektur] wusste das ganze Team stets, was insgesamt ansteht und in welchem Bereich sie aktuell agieren.

Ich bin sehr zufrieden mit dem Ergebnis unseres Teams und freue mich, dass ich im Rahmen dieses Moduls wertvolle Erfahrungen sammeln konnte.
