= Einzelreflexion: Conrad Caffier

* Teamrollen: Implementierung/Tests

Im ersten Semester war ich hauptsächlich unterstützend im Bereich Projektleitung aktiv. Dabei war es noch schwierig effizient im Team zusammen zu arbeiten. Wir traffen uns einmal pro Woche, also zwei mal pro Iteration, um Fortschritte, neue Erkenntnisse und die Aufgabenaufteilung abzusprechen. Dabei konnte man beobachten wie Woche für Woche das Team besser zusammen wuchs und sich effektiver abstimmte.

Ich konnte hier erste Erfahrungen mit der Arbeit mit Asciidoc erlangen und habe im Bereich Planung und Umsetzung größerer Software Projekte viele neue Erkenntnisse gewinnen können. Mein größter Lernprozess fand jedoch im zweiten Semester statt. Hier wurde mehr Zeit in die Entwicklung unserer Software gesteckt. Durch die agile Softwareentwickung haben wir uns als Team auf verschiedene Aufgabenbereiche spezialisieren können. So gab es Entwickler die sich auf die Backend-Entwicklung konzentriert haben, während meine Aufmerksamkeit der Frontend-Entwicklung galt. Da ich nur wenig Erfahrung in der Programmierung von Webanwendungen bisher vorweisen konnte, stellte sich dies als große Herausforderung für mich da.

Konkret möchte ich hier auf die Entwicklung meiner ersten komplexeren Page eingehen: die RegisterPage. Wie der Name schon vermuten lässt, ist dies eine Seite zur Anlegung neuer Piloten/Nutzer. Hauptsächlich waren dementsprechend Eingabefelder für die Daten des zu registrienden Nutzers und Buttons zur Auswahl einiger Details gefragt.
Anfangs habe ich mir grundlegendes Wissen im Internet über die mir neuen Tools Vue.js und Typescript erarbeitet. Dieses stellte sich auch schnell als nützlich heraus als ich meine ersten Pages entwickelte. Jedoch wichen diese stark vom restlichen Layout der Webanwendung ab. Somit orintierte ich mich stärker an dem optischen Layout des bereits bestehenden Prototyps. Hier war es für mich sinnvoll die Code-Dateien innig zu studieren um die Formation einzelner Elemente übernehmen zu können und auf meine Anforderungen anzupassen. Nach dem ich verstanden hatte wie die Website grundlegend aufgebaut sein musste, um gleich auszusehen wie alle anderen, konnte man fast alle Formatierungen übernehmen und kam so wesentlich schneller voran. Dies half mir auch extrem bei meiner RegisterPage, da ich vorher bereits eine LoginPage gestaltet hatte. Die RegisterPage war dementsprechend ähnlich aufgebaut. Hier halfen mir die Arbeit in Iterationen sehr, da man klare Aufgaben und zeitliche Zielsetzungen dazu hatte. Dabei möchte ich ein Dankeschön an Jakob aus meinem Team aussprechen, der jeder Zeit mir Antworten auf meine Fragen geben konnte. häufig hilft da auch das vier Augenprinzip, wenn man seinen eigenen Tippfehler nicht mehr finden kann.

Ich bin sehr stolz Teil des Teams zu sein und mit meinen Komilitonen gemeinsam das Projekt durchgeführt zu haben. Es ist mein erstes Mal gewesen im Team ein größeres Software-Projekt umzusetzen. Hier zu sehen wie sich Stück für Stück etwas aufbaut und wächst ist sehr faszinierend zu beobachten. Dies ist eine wichtige Erfahrung für mich und hat mir viele wichtige Dinge für mein weiteres Studium und mein darauffolgendes Arbeitsleben gelehrt. Ich hoffe einige Erfahrungen bereits im fünften Semester bei meinem Praktikum anzuwenden.

