@startuml domainmodel
left to right direction
"Admin" as ac01
"Pilot" as ac02
package Benutzerbereich {
    "UC02 Account anmelden" as (uc02) 
    "UC03 Protokoll anlegen" as (uc03)
    "UC04 Protokolle einsehen" as (uc04)
    "UC05 Flugleiter bestimmen" as (uc05)
    "UC06 Account abmelden" as (uc06)
    "UC09 Protokoll bearbeiten" as (uc09)
}

package Administrationsbereich {
    "UC01 Account registrieren" as (uc01)
    "UC07 Accountdaten modifizieren" as (uc07)
    "UC08 Account deaktivieren" as (uc08)

}
ac01 -d-> uc01
ac01 -u-> uc04
ac01 -d-> uc07
ac01 -d-> uc08
ac01 -u-> uc09
ac02 -d-> uc02
ac02 -d-> uc06
ac02 -u-> uc09
ac02 -u-> uc04
ac02 -d-> uc03
ac02 -d-> uc05
@enduml
