= Entwicklerdokumentation

== Entwicklungsumgebung

Nachfolgend sind die Tools aufgelistet, die für die Entwicklung der Anwendung benötigt werden. Teilweise sind Anweisungen für die Installation unter Windows enthalten. Auf Linux können die Pakete über den Paketmanager installiert werden.

=== Backend

- IntelliJ IDEA (Ultimate Edition wenn auch Frontend)
- Java 17+ `winget install EclipseAdoptium.Temurin.21.JDK`
- Gradle

=== Frontend

- IntelliJ IDEA (Ultimate Edition)
- **und/oder** Visual Studio Code
- Node.js `winget install OpenJS.NodeJS`
- pnpm `winget install pnpm.pnpm`

=== Datenbank

- PostgreSQL mit Docker https://docs.docker.com/get-docker/

Nachfolgend die `docker-compose.yml` Datei für die Datenbank:

[source,yaml]
----
services:
  db:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: logbook
      POSTGRES_PASSWORD: logbook
      POSTGRES_DB: logbook
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8081:8080
----

Diese an eine geeignete Stelle auf dem eigenen Rechner speichern und mit `docker-compose up -d` starten.

Nun ist die Datenbank unter `localhost:5432` und das Admin-Interface unter `localhost:8081` erreichbar.

== Starten der Anwendung in der Entwicklungsumgebung

Im Terminal in den Projektordner wechseln. Dann in den `backend` Ordner wechseln und die Anwendung starten.

[source,bash]
----
cd src/backend
----

[source,bash]
----
# auf Linux
./gradlew runFullstackApp
# auf Windows
./gradlew.bat runFullstackApp
----

=== Konfiguration nach dem ersten Start

Mit dem ersten Start wird eine `config.toml` im `config` Ordner erstellt. Diese Datei enthält die Konfiguration für die Anwendung. Hier können die Einstellungen für die Datenbankverbindung und den Serverport angepasst werden, sowie der **Entwicklungmodus** aktiviert werden.

[source,toml]
----

----
