== Reflexion zur Strukturierung und Implementierung der Routen im Backend - Julian Neidert

Im Rahmen unseres Software-Projekts bestand eine wesentliche Herausforderung darin, ein effektives und sinnvolles Routing-System im Backend zu implementieren. Dies ist entscheidend für die Verwaltung der verschiedenen Endpunkte unserer API, über die das Frontend auf Daten zugreifen und diese manipulieren kann. Die Komplexität des Projekts erforderte eine sorgfältige Planung und Implementierung der Routen, um eine reibungslose Kommunikation zwischen Frontend, Backend und Datenbank sicherzustellen.

Im Software-Engineering Prozess kann man diese Aufgabe hauptsächlich den Phasen des Entwurfs und der Implementierung zuordnen:

* *Entwurf*: Analyse und Strukturierung der benötigten Routen basierend auf den Anforderungen und Use Cases.
* *Implementierung*: Entwicklung der Routen und ihrer Funktionalitäten, Verknüpfung mit Datenbank.

Das Routing im Kontext unserer API umfasst die klare Definition von Endpunkten und den entsprechenden HTTP-Methoden (GET, POST, PUT, DELETE), die für den Zugriff auf und die Manipulation von Daten verwendet werden. Um dieses System zu entwickeln, begann ich mit einer umfassenden Analyse der funktionalen Anforderungen und link:https://github.com/jakobkmar/E09-modellflug-logbuch/blob/main/docs/requirements/use-case_model.adoc[UseCases] unserer Anwendung. Basierend auf diesen Anforderungen habe ich eine detaillierte Übersicht der benötigten API-Endpunkte erstellt. Diese Endpunkte habe ich in logische Gruppen gegliedert, die jeweils bestimmte Aspekte unserer Anwendung abdecken. Zu dem Zeitpunkt wollte ich die Routen in einer Datei in Flugleiter-, Admin-, Nutzer- und Flugeintragrouten unterteilen.

Die Gruppierung der Endpunkte in logische Einheiten unterstützt auch das Prinzip der Trennung von Anliegen (Separation of Concerns), indem sie sicherstellt, dass jede API-Ressource eine klar abgegrenzte Verantwortlichkeit hat. Dies fördert nicht nur eine saubere Code-Architektur und Code-Qualität, sondern erleichtert auch zukünftige Erweiterungen und Änderungen, da Änderungen in einem Bereich der Anwendung weniger wahrscheinlich Auswirkungen auf andere Bereiche haben.

Die *Implementierung* begann mit der Erstellung der grundlegenden Endpunkte. Ich habe mich dabei mit dem anderen Backend-Entwickler auf gewisse Code Conventions geeinigt, beziehungsweise seine übernommen, da er mehr Erfahrung mit Kotlin hat und wir so auf einer gemeinsamen Grundlage entwickeln konnten. Also habe ich nach und nach die verschiedenen HTTP-Methoden den entsprechenden Endpunkten zugeordnet und die Funktionalität der Routen schrittweise implementiert. Dabei traten jedoch einige Probleme auf.

. *Kommunikation mit der Datenbank*: Ich hatte mich zuvor noch nicht ausreichend damit beschäftigt, wie die Kommunikation mit der Datenbank stattfinden soll. Um diese Arbeit zu erleichtern habe ich in Absprache mit unserem anderen Backend Entwickler ab sofort sqldelight, ein Compiler plugin für Kotlin, verwendet. Mit diesem konnte ich mit Grundlage der Tabellenstruktur der SQL Tabellen einfache SQL Statements schreiben, welche dann halbautomatisch zu  Kotlin Code generiert wurden, welchen ich dann normal als Funktionsaufruf in den Dateien verwenden konnte. Die zugehörigen Files liegen in diesem link:https://github.com/jakobkmar/E09-modellflug-logbuch/tree/main/src/backend/src/main/sqldelight/de/mfcrossendorf[Ordner]. +
Manchmal gab es dann Probleme bei der Implementierung, dass Daten nicht richtig gespeichert oder abgerufen werden konnten. Diese Fehler konnte ich aber durch die Funktionen von IntelliJ Ultimate schnell finden.

. *zu viel in einer Datei:* Ich hatte zuerst alle Routen in einer Datei, was nach und nach zu unübersichtlichem Code führte. Nachdem ich die Routen in verschiedene Dateien aufgeteilt und noch einmal die Gliederung leicht angepasst hatte, war der Code viel besser strukturiert und leichter zu warten. So habe ich die Routen in AccountRoutes, FlightDirectorRoutes und FlightlogRoutes unterteilt. +
 link:https://github.com/jakobkmar/E09-modellflug-logbuch/tree/main/src/backend/src/main/kotlin/de/mfcrossendorf/logbook/routes[Ordner mit Routen] +
Außerdem habe ich nach einem Hinweis von einem Teammitglied die Struktur einer Route überarbeitet, weil ich in einer Route mit Nutzer-ID weitere Routen hatte, für welche jedoch diese Information gar nicht notwendig war.

. *Integration mit dem Frontend*: Es gab kleine Missverständnisse bezüglich der erwarteten API-Responses und es wurden Kleinigkeiten an der Datenbankstruktur angepasst. Diese Probleme konnten aber sehr schnell nach kurzer Absprache mit den zuständigen Teammitgliedern gelöst werden.

== Bewertung und Fazit

Meine Lösung funktionierte bei meinen Überprüfungen mithilfe der Fehleranalyse von IntelliJ und nach den zu dem Zeitpunkt mir bekannten Anforderungen ohne Probleme. Die endgültige Verknüpfung mit dem Frontend hat anschließend ein Teamkollege gemacht. Dabei kam es zu minimalen Anpassungen, weil unter anderem eine Spalte in der Datenbank überarbeitet werden musste, aber die Routen und die API-Responses waren korrekt und mein Teamkollege war sehr zufrieden mit dieser Vorarbeit.

Bei der Bearbeitung dieser Aufgabe habe ich gelernt, wie wichtig eine klare und gut strukturierte Planung im Vorfeld ist. Zudem habe ich erlebt, dass die Kommunikation innerhalb des Teams entscheidend ist, um Missverständnisse zu vermeiden und vorzubeugen. Ein sehr wichtiger Aspekt, welcher meinen Erfolg entscheidend beeinflusst hat, war, dass ich mich nicht gescheut habe, bei Problemen oder Unklarheiten einen wesentlich erfahreneren Backend-Entwickler um Hilfe zu bitten. Dies hat mir geholfen, schnell Lösungen zu finden und meine Arbeit effektiv erledigen zu können.

