==== Conrad Caffier
.Teamrollen: Frontendentwicklung/Implementierung

Im ersten Semester habe ich meine konkrete Rolle nicht wirklichen finden können. In dieser Zeit gab es viele verschiedene Aufgaben. Dadurch haben wir in unserem Team nur schwierig eine faire Aufteilung zustande bekommen. Dies führte dazu, dass die Projektleitung und ein weiterer Komilitione sicherlich mehr Zeit und Nerven investiert haben als der Rest des Teams.
Konkret habe ich in dieser Zeit hauptsächlich Iterationspläne und weitere Projektmanagement-Aufgaben begleitet. Ab der vierten Iteration habe ich dann weitere umfassendere Aufgaben gelöst wie beispielsweise die Bearbeitung der Test Cases.

Im zweiten Semester begann dann ganzheitlich die intensive Arbeit am Prototypen. Hier habe ich meine Hauptaufgabe mit der Frontendentwicklung gefunden. Anfangs hatte ich dabei große Schwierigkeiten, da meine Vorkenntnisse im Bereich Web-Development begrenzt waren. Doch diese legten sich zeitnah. Durch die Vorlesungen und Prakitka habe ich mehr und mehr Wissen im Bereich iterativer und agiler Softwareentwicklung sammeln können. Dabei habe ich vorallem die Arbeit in Iterationen sehr geschätzt, weil man einen guten Überblick über die Ziele in einem kurzfristigen Zeitraum behalten hat. Somit konnte das ganze Projekt langsam und stetig wachsen ohne auch eher unwichtige Aufgaben hinter den dringenderen Aufgaben zu vergessen.

Ich habe hier meine Fähigkeiten im Design der UI von verschiedenen Pages stark verbessert. Geholfen hat mir hier ein einheitliches Bild der gesamten Website zu generieren, da man so an bereits bestehenden Pages Orientierungsbeispiele hatte. An dieser Stelle möchte ich ein besonderes Dankeschön an Jakob aus meinem Team aussprechen, der mir dort zu jeder Zeit helfen konnte und auf alle meine Fragen eine Antwort parat hatte.

Wie bereits angesprochen, gab es einige Probleme im Team was die gleichmäßige Aufteilung der Aufgaben anging. Dies lag wohl an der zu seltenen Anwesenheit eines Teammitgliedes. Welches dann auch seine Aufgaben nicht den Anforderungen entsprechend gelöst hat. Was wiederum dazu führte, dass andere dort gründlich prüfen und nicht nur einmal nacharbeiten mussten. Jedoch muss man auch erwähnen, dass einzelne Aufgaben nur von bestimmten Personen erledigt werden konnten, da nur diese in dem bestimmten Thema eingearbeitet waren und dort einen großeren Wissenspool hatten aus dem Sie schöpfen konnten. Dementsprechend würde ich zum Teil die Aufgabenverteilung als problematisch ansprechen. Auch wenn diese im Verlauf des Projektes, über diese zwei Semester, deutlich besser geworden ist.

Ich denke die positiven Erkenntnisse aus dem Projekt überwiegen trotzdem. Hier kann ich meinerseits eine große Wissenserweiterung sowohl durch die Vorlesungen und Praktikas, als auch die direkte Umsetzung und das praktische Arbeiten nennen. Im Team ist die Kommunikation immer besser geworden und man hat gemeinsam in kurzer Zeit mehr geschafft. Das Anwenden gelehrter Praktiken wie beispielsweise eine Work Item List und genaue zeitliche Zielsetzungen werde ich in meinen Alltag übernehmen. So hat man auch wenn es nicht nur um Softwareentwicklung geht einen guten Überblick und sieht was dringend erledigt werden muss und welche Themen eher etwas warten müssen.

Alles in allem möchte ich zahlreiche Erkenntnisse aus Dokumentation, Implementierung und Teamarbeit positiv hervorheben. Das Gelernte kann definitiv bei weiteren Softwareprojekten und im weiteren Studeinverlauf angewendet werden. Ich denke auch in meinem mir im nächsten Semester bevorstehenden Praktikum wird vieles daraus Anwendung finden.
